import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className="">
      <main className="m-auto max-w-screen-lg px-8 p-11">  
      {children}
      </main>
      </body>
    </html>
  );
}
